name: Build + cppcheck

on: push

jobs:
  build-cppcheck:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Pull git submodules
      run: git submodule update --init --recursive
    - name: Install build dependencies
      run: sudo apt update && sudo apt install debhelper libusb-1.0-0-dev libpulse-dev cppcheck
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }} 
    - name: Build G19daemon
      run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && make
    - name: CppCheck
      run: cppcheck --project=build/compile_commands.json
